Add HTTP client
julianneswinoga/flightgear-python pull request #9
Opened 2023-11-06 14:56 UTC by juhannc

This PR adds an HTTP client to access (and manipulate) the property tree.

The HTTP method not only doesn't require an additional socket, it is also faster than the telnet client. Using the following script, I got a speedup of around 1-1.1x for a single request and 1.6-1.9x for 100 consecutively requests.

```python
#!/usr/bin/python3
import time

from flightgear_python.fg_if import HTTPConnection, PropsConnection

PROPERTY = "/velocities/airspeed-kt"
NUM_REQUESTS = 100

telnet_conn = PropsConnection("localhost", 5500)
telnet_conn.connect()
http_conn = HTTPConnection("localhost", 5050)

# Single property access
t0 = time.time()
telnet_conn.get_prop(PROPERTY)
t1 = time.time()
t_telnet = t1 - t0

t0 = time.time()
http_conn.get_prop(PROPERTY)
t1 = time.time()
t_http = t1 - t0

print(f"Telnet: {t_telnet:.6f}s")
print(f"HTTP: {t_http:.6f}s")
print(f"Speedup using HTTP for a single request: {t_telnet/t_http:.2f}x")

# Multiple property access
t0 = time.time()
for _ in range(NUM_REQUESTS):
    telnet_conn.get_prop(PROPERTY)
t1 = time.time()
t_telnet = t1 - t0

t0 = time.time()
for _ in range(NUM_REQUESTS):
    http_conn.get_prop(PROPERTY)
t1 = time.time()
t_http = t1 - t0

print(f"Telnet: {t_telnet:.6f}s")
print(f"HTTP: {t_http:.6f}s")
print(f"Speedup using HTTP for {NUM_REQUESTS} requests: {t_telnet/t_http:.2f}x")
```

2023-11-06 18:48 UTC, julianneswinoga commented
Thank you so much for submitting a feature!! :star_struck: :star_struck: 
I don't have a lot of time to review stuff in-depth right now (travelling) but a couple minor things that are easy to add:
- Add your example into the documentation files (you can just copy how it was done for other examples)
- Check off that `HTTP` box in the `README.md`!!!!

(no problem if you can't add that stuff, I can just add it later :smiley: )

2023-11-06 19:32 UTC, juhannc commented
> Thank you so much for submitting a feature!! 🤩 🤩

Happy to help developing a tool I use on the daily 😊

> * Add your example into the documentation files (you can just copy how it was done for other examples)
> * Check off that `HTTP` box in the `README.md`!!!!

Good points, did that 👍🏼

2023-11-07 14:35 UTC, julianneswinoga requested changes
Overall I think this is great! Thank you very much for taking the time :smile: 
I do see a lot of similarities between `HTTPConnection` and `PropsConnection` though, so I think in the future I'll try to consolidate them as much as I can. I see just a couple blockers before this can be merged though.

Additionally it would be nice (but not required! I can add this later) to have some unit tests. :)

2023-11-07 14:46 UTC, juhannc commented on flightgear_python/fg_if.py
> -import re
Don't know how this could have happend 🙈 
Fixed in 36bf633e03ed8c6e923e7ba9e6b202d4f2be5544

2023-11-07 14:46 UTC, juhannc commented on flightgear_python/fg_if.py
> +
Fixed in 36bf633e03ed8c6e923e7ba9e6b202d4f2be5544

2023-11-07 14:46 UTC, juhannc commented on flightgear_python/fg_if.py
> +    def __init__(self, host: str, tcp_port: int, rx_timeout_s: float = 2.0):
Fixed in 36bf633e03ed8c6e923e7ba9e6b202d4f2be5544

2023-11-08 07:09 UTC, julianneswinoga commented
Yeah I think I'd want to rename `PropsConnection` to something like `TelnetConnection` so it would be a breaking change. I'll handle that at a later point though.

There already is a testsuite (under `tests`) and an entire CircleCI pipeline, but I don't think I have it properly configured for PRs yet (as yours is the first!). 

I've used `black` recently with a different project and I like it, so I think I'll be adding it to this and all other Python projects.

2023-11-08 07:09 UTC, julianneswinoga approved these changes

2023-11-08 07:10 UTC, merged